export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGRREDIENTS = 'SET_INGRREDIENTS'
export const SET_INGRREDIENTS_FAILED = 'SET_INGRREDIENTS_FAILED'